// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACJAQWPuNtOk9cYamfm4X23ANR-vKi4cA',
    appId: '1:613122717756:web:5d3c75558648ba6b5a6b39',
    messagingSenderId: '613122717756',
    projectId: 'machinetasktotalx',
    authDomain: 'machinetasktotalx.firebaseapp.com',
    storageBucket: 'machinetasktotalx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdxKAn1gjT54Xe0vJ6zVEJRNZr08wTVdI',
    appId: '1:613122717756:android:b398613451084c605a6b39',
    messagingSenderId: '613122717756',
    projectId: 'machinetasktotalx',
    storageBucket: 'machinetasktotalx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBo86b43GQiE1sANaEhBa95R2e0Iix3Vs',
    appId: '1:613122717756:ios:c55b0840880afd925a6b39',
    messagingSenderId: '613122717756',
    projectId: 'machinetasktotalx',
    storageBucket: 'machinetasktotalx.firebasestorage.app',
    iosBundleId: 'com.example.machineTestTotalx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACJAQWPuNtOk9cYamfm4X23ANR-vKi4cA',
    appId: '1:613122717756:web:8a61f37cfe97ae465a6b39',
    messagingSenderId: '613122717756',
    projectId: 'machinetasktotalx',
    authDomain: 'machinetasktotalx.firebaseapp.com',
    storageBucket: 'machinetasktotalx.firebasestorage.app',
  );
}